services:
    _defaults:
        autoconfigure: true

    Thepixture\TestElementBundle\Controller\ContentElement: ~

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]
